### ISSUE TITLE
Registering or queueing identical GGs should be flagged

### ISSUE THREAD

**Issue by bthuronyi** [bthuronyi/CloneCoordinate#39] opened 2024-06-13 16:11 UTC
Right now, neither the Registry nor the Golden Gate tab checks whether the queued construct has been queued before identically, i.e. with the same rIDs in the same order. One place or the other should throw an error that identifies the existing/duplicate construct for the user as it's queued. The reason to put this check in the GG tab is that this is where construct rIDs are entered, and that process often occurs before Registration anyway. If Registration happens first, the Registry won't throw the error until rIDs are entered on the GG tab anyway, meaning it won't be seen by the user immediately. But it probably makes sense to compile rIDs based on gID entries in the Registry line and then cross-check them in GG Status. Just need to make sure it isn't circular.

**Comment by evelynqi** [comment] 2024-07-12 00:06
> Right now, neither the Registry nor the Golden Gate tab checks whether the queued construct has been queued before identically

Registry has an rID composition of gg constructs (Registry BM) which I have named Registry_GG_rID_composition. I was going to use it for a regexmatch expression that appended this code after all the code in queueing validity check: 
"
"&
if(isnumber(match(index(Registry_GG_rID_composition, xmatch($E652,Registry_Construct_name)),Registry_GG_rID_composition,0)), "duplicate construct", ""))
___________________________________________________________________________________________________________________________________
However, I noticed that in the Registry, the status already has code for if a construct is a duplicate of another one with the same rIDs in the same order using the same/similar logic as I have written above. Therefore, in validity queueing check in the Golden Gate sheet, I have used a regexmatch expression to look up if the gg construct's status in registry has "duplicate" in it. No circular logic there. Also wanted to point out that all of this is in queueing validity check, so there is no change in status. This is fine since  the users would need to certify correctly queued and would see the queueing validity check message ideally before they checked the box to certify. I'm not sure how informative the message should be: in theory, I think duplicate construct is enough and they can check the registry but it also may be nice to see which construct it is the same as. The new code is implemented in the last few lines. 

=if(N651="","",
iferror(if(and(DU651:ED651),"valid junctions","INVALID junctions!")&"
"&
ifs(
countblank(EE651:EN651)=column(EN651)-column(EE651)+1,"no mIDs used yet",
and(EE651:EN651),"valid mIDs",
TRUE,"INVALID mID! "&join(" ",byrow(filter(AV651:BE651,EE651:EN651=FALSE),lambda(row,row&"="&index(Registry_GG_parts_display_name,xmatch(index(Minipreps_m_Construct_name,xmatch(row,Minipreps_m_ID)),Registry_Construct_name)))))&"
"&
if(and(byrow(filter(AV651:BE651,EE651:EN651=FALSE),lambda(row,
let(ActualmIDConstructName,index(Minipreps_m_Construct_name,xmatch(row,Minipreps_m_ID)),
and(
index(Registry_5_overhang,xmatch(ActualmIDConstructName,Registry_Construct_name))=index(Registry_5_overhang,xmatch(DQ651,Registry_ID)),
index(Registry_3_overhang,xmatch(ActualmIDConstructName,Registry_Construct_name))=index(Registry_3_overhang,xmatch(DQ651,Registry_ID))))))),
"junctions remain valid","INVALID junctions")),
"Validity check function error!")**&"
"&
if(regexmatch(index(Registry_Status, xmatch($E651,Registry_Construct_name)),"duplicate"), "duplicate construct", ""))**

**Comment by evelynqi** [comment] 2024-07-12 00:07
https://docs.google.com/spreadsheets/d/1HVUX3gIyUeDDFw8sH8zxhATD_4YwlsOI0P_Yx6G_tUQ/edit?usp=sharing

**Comment by bthuronyi** [comment] 2024-07-12 14:03
> However, I noticed that in the Registry, the status already has code for if a construct is a duplicate of another one with the same rIDs in the same order using the same/similar logic as I have written above.

Hahah whoops, this does happen sometimes -- when we didn't used to have strong Issue tracking, I would sometimes fix/implement something but forget to resolve the Comment corresponding to it or check it off my hand-written list...

**Comment by bthuronyi** [comment] 2024-07-12 14:09
That said, I don't love how I did this, since it permanently changes the Status of the construct to "p### duplicate?". Maybe there is no situation where we would want to keep that duplicated construct, though, and the proper resolution is to Abandon it.

Looks like the gID queueing validity check code works! I agree it would be nice to pull the duplicate information. You can actually do that by just displaying the Registry Status of that construct, since it already shows that. Go ahead and implement in main CC. Please make it say "duplicate construct!" with the exclamation point since this is a fairly significant problem. This will trigger conditional formatting (which we should make consistent soon -- I will add a new issue).

**Comment by evelynqi** [comment] 2024-07-12 19:20
Implemented and tested!

**Closed as completed by evelynqi** 2024-07-12 19:20 UTC
Labels: type:enhancement, entity:Golden Gate g, entity:Registry, Not Essential for Release, type: Status
